{
  "openapi": "3.0.1",
  info:
    title: REST
    version: 0.0.1
  ,
  "tags": [
    {
      "name": "TODO controller",
      "description": "Controller with simple rest methods"
    }
  ],
  "paths": {
    "/v1/api": {
      "get": {
        "tags": [
          "TODO controller"
        ],
        "summary": "Get all task",
        "operationId": "getAllTask",
        "responses": {
          "200": {
            "description": "Get array with task",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "5XX": {
            "description": "See reason in error message",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ErrorResponse"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "TODO controller"
        ],
        "summary": "Create new task",
        "operationId": "create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TaskDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "New task",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Task"
                  }
                }
              }
            }
          },
          "400": {
            "description": "This task already exist by title",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ErrorResponse"
                  }
                }
              }
            }
          },
          "5XX": {
            "description": "See reason in error message",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ErrorResponse"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/api/update/{id}": {
      "post": {
        "tags": [
          "TODO controller"
        ],
        "summary": "Refresh task by id",
        "operationId": "update",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Task's id",
            "required": true,
            "schema": {
              "minimum": 1,
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TaskDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "New task",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Task"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Couldn't find task by id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ErrorResponse"
                  }
                }
              }
            }
          },
          "5XX": {
            "description": "See reason in error message",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ErrorResponse"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/api/{id}": {
      "get": {
        "tags": [
          "TODO controller"
        ],
        "summary": "Delete task by id",
        "operationId": "deleteTaskById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Task's id",
            "required": true,
            "schema": {
              "minimum": 1,
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Task was deleted",
            "content": {
              "application/json": { }
            }
          },
          "400": {
            "description": "Couldn't find task by id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ErrorResponse"
                  }
                }
              }
            }
          },
          "5XX": {
            "description": "See reason in error message",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ErrorResponse"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Task": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Сообщение об ошибке"
          },
          "code": {
            "type": "string",
            "description": "Код ошибки"
          }
        },
        "description": "Объект ошибки"
      },
      "TaskDto": {
        "required": [
          "description",
          "title"
        ],
        "type": "object",
        "properties": {
          "title": {
            "maxLength": 100,
            "minLength": 0,
            "type": "string",
            "description": "Task title",
            "example": "Fix bug"
          },
          "description": {
            "maxLength": 1000,
            "minLength": 0,
            "type": "string",
            "description": "Description",
            "example": "Task description"
          }
        },
        "description": "Body task"
      }
    }
  }
}