spring:
  jpa:
    open-in-view: false
    show-sql: true
  banner:
    location: banner.txt
  r2dbc:
    url: ${HOST_DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    port: ${DB_PORT}
    host: ${DB_HOST}
    databaseName: ${DB_NAME}
  flyway:
    url: ${HOST_DB}
    baselineOnMigrate: true
    enabled: true