spring:
  jpa:
    open-in-view: false
    show-sql: true
  banner:
    location: banner.txt
  datasource:
    url: ${HOST_DB:jdbc:postgresql://localhost:5432/rest}
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
    driver-class-name: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true
    enabled: true